name: heymax_analytics
version: "1.0.0"
config-version: 2

profile: heymax_analytics

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  heymax_analytics:
    +materialized: view
    staging:
      +schema: stg
      +tags: ["staging"]
    marts:
      +schema: mart
      +tags: ["mart"]
      core:
        +materialized: table
      growth:
        +materialized: table
      retention:
        +materialized: table
      engagement:
        +materialized: table
